DEFINES*=BOOST_CHRONO_SOURCE
DEFINES*=BOOST_DATE_TIME_SOURCE
DEFINES*=BOOST_FILESYSTEM_SOURCE
DEFINES*=BOOST_REGEX_SOURCE
DEFINES*=BOOST_SYSTEM_SOURCE

include($$PWD/boost_dyn.pri)
include($$PWD/boost_source.pri)
